Arguments:
  filename: image.png
  contrast: 1
  sampleSize: 16x16
  contrastbreak: 128
  output: 
    default: null
    const: output.txt
  blur: 30
  palettename: null
  hide: False
  characters: \'^:!=*$%@#
  characterfile: null
  foreground: True
  background: True